services:
  - type: web
    name: a-to-z-weld-and-build-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TO_EMAIL
        value: atozweldbulidcontact@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: CORS_ORIGIN
        sync: false
